apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployfrontend
  labels:
    app: deployfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployfrontend
  template:
    metadata:
      labels:
        app: deployfrontend
    spec:
      containers:
      - name: deployfrontend
        image: 373474467195.dkr.ecr.us-east-1.amazonaws.com/sample_ecs:main-97c6d47
        ports:
        - containerPort: 80
