apiVersion: v1
kind: Service
metadata:
  name: servicefrontend
spec:
  selector:
    app: deployfrontend
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
